workflows:
  android-app:
    name: Android app
    environment:    
      java: 17.0.9
      # groups:
      # - firebase_credentials
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    # publishing:
    #   firebase:
    #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    #     android:
    #       app_id: 1:930216494956:android:5febe53ee6f0eeb4155549  
    #       groups:
    #         - androidTesters
    #       artifact_type: 'apk' # Replace with 'aab' to only publish the Android app bundle 
