workflows:
  native-android:
    name: Native Android
    instance_type: mac_mini_m1
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Install Java 17
        script: |
          echo $VERSION
          brew update
          brew install openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - name: Build Android release
        script: | 
          chmod +x ./gradlew
          ./gradlew assembleRelease -PversionCode=1 -PversionName=1.0.0