workflows:
  android-app:
    name: Android app
    environment:    
      java: 17.0.11
      groups:
      - browserstack
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
      - name: MANUAL Upload APK to BrowserStack
        script: |
          response=$(curl -u "balajiabiraman_dhEuiL:f8xXkagrkJzDBMDi1bJQ" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "file=@./appium_tests/android/Skelton App Final.apk" \
          -F "custom_id=trc-skeleton-app") 
          echo "export APP_URL=$(echo $response | jq -r '.app_url')" > app_url.sh
          echo $response > temp.sh
      - name: Install BrowserStack SDK and Run Tests
        script: |
          cd ./appium_tests/android
          pip install browserstack-sdk
          browserstack-sdk pytest pytest_main.py
          
    artifacts:
      - app/build/outputs/apk/release/*.apk
   
      

      
    # publishing:
    #   firebase:
    #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    #     android:
    #       app_id: 1:930216494956:android:5febe53ee6f0eeb4155549  
    #       groups:
    #         - androidTesters
    #       artifact_type: 'apk' # Replace with 'aab' to only publish the Android app bundle 
