workflows:
  android-app:
    name: Android app
    environment:    
      java: 17.0.11
      groups:
      - browserstack
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
      - name: Prepare BrowserStack Config
        script: |
          sed -i '' -e "s/\${userName}/${userName}/g" appium_tests/android/browserstack.yml
          sed -i '' -e "s/\${accessKey}/${accessKey}/g" appium_tests/android/browserstack.yml
      - name: MANUAL Upload APK to BrowserStack
        script: |
          apk_file=$(echo ./app/build/outputs/apk/release/*.apk)
          response=$(curl -u "${userName}:${accessKey}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "file=@${apk_file}" \
          -F "custom_id=trc-skeleton-app") 
      - name: Install BrowserStack SDK and Run Tests
        script: |
          cd ./appium_tests/android
          pip install browserstack-sdk
          browserstack-sdk pytest pytest_main.py
          
    artifacts:
      - app/build/outputs/apk/release/*.apk
   
      

      
    # publishing:
    #   firebase:
    #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    #     android:
    #       app_id: 1:930216494956:android:5febe53ee6f0eeb4155549  
    #       groups:
    #         - androidTesters
    #       artifact_type: 'apk' # Replace with 'aab' to only publish the Android app bundle 
