workflows:
  native-android:
    name: Native Android

    scripts:
      - name: Install Java 17
        script: |
          echo java -version
          brew update
          brew install openjdk-17-jdk
          export JAVA_HOME: /usr/local/opt/openjdk@17
      - name: Set Android SDK location
        script: | 
          java -version
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: | 
          java -version
          chmod +x ./gradlew
          ./gradlew assembleRelease -PversionCode=1 -PversionName=1.0.0